import {TYPES,money,cents,norm,balance,daily,yesterday} from './model.js';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi'}).format(new Date());
let cloud,session=null,records=[],loaded=false,view='khata',selected=null,tab='all',date=today(),unsub=null,importDraft=null;
const all=type=>records.filter(x=>x.type===type&&!x.deleted),parties=()=>all('party'),entries=()=>all('entry'),closings=()=>all('closing'),party=id=>parties().find(p=>p.id===id),owner=()=>session?.role==='owner';
function notice(t){$('toast').textContent=t;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,5000)}
function error(e){notice(e.code==='permission-denied'?'Ijazat nahi mili. Malik supplied rules publish karein.':e.message||'Save nahi hua');console.error(e)}
function modal(title,html){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;if(!$('dialog').open)$('dialog').showModal()}
$('close').onclick=()=>$('dialog').close();
function route(v,id=null){view=v;selected=id;$('search').value='';$('from').value=$('to').value='';render();window.scrollTo(0,0)}
$('back').onclick=()=>route('khata');$('khataNav').onclick=()=>route('khata');$('dailyNav').onclick=()=>route('daily');$('expenseNav').onclick=()=>route('expenses');$('cashNav').onclick=()=>route('cash');
$('search').oninput=render;$('from').onchange=$('to').onchange=render;
$('tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b){tab=b.dataset.tab;render()}};
function accountMatches(p,q){return norm(p.name+' '+(p.phone||'')+' '+(p.details||'')).includes(norm(q))|| (!!q.replace(/\D/g,'')&&(p.phone||'').replace(/\D/g,'').includes(q.replace(/\D/g,'')))}
function matches(e){const q=norm($('search').value);return (!q||norm((party(e.partyId)?.name||e.account||'')+' '+e.note+' '+TYPES[e.kind]).includes(q))&&(!$('from').value||e.date>=$('from').value)&&(!$('to').value||e.date<=$('to').value)}
function entryHTML(rows){return rows.sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt).map(e=>`<div class="entry"><div class="note"><b>${esc(TYPES[e.kind])}</b><small>${esc(e.date)} · ${esc(party(e.partyId)?.name||e.account||'')}</small>${esc(e.note||'')}${owner()?`<br><button data-edit="${esc(e.id)}">Edit</button>`:''}</div><strong class="red">${['payment','expense','credit'].includes(e.kind)?money(e.amount):'—'}</strong><strong class="green">${['collection','sale','borrow'].includes(e.kind)?money(e.amount):'—'}</strong></div>`).join('')||'<div class="empty">Abhi koi entry nahi.</div>'}
function render(){if(!session)return;const p=party(selected),q=$('search').value;$('back').hidden=!selected;$('tabs').hidden=view!=='khata'||!!selected;$('detailTools').hidden=!selected;$('title').textContent=p?.name||({khata:'Mera Khata',daily:'Daily Sale',expenses:'Akhrajat accounts',cash:'Closing Cash'})[view];$('search').placeholder=selected?'Entry / note search karein':'Naam ya mobile number search karein';
 $('tabs').querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab));
 const es=entries();if(view==='khata'){
 if(p){const b=balance(p,es);$('summary').innerHTML=`<div><strong class="${b>=0?'red':'green'}">${money(Math.abs(b))}</strong><small>${b>0?'Hum ne lene hain':b<0?'Hum ne dene hain':'Hisaab barabar'} · ${esc(p.phone||'')}</small></div>`;$('list').innerHTML=`<p class="stat-note">Opening: ${money(Math.abs(p.opening||0))} · ${(p.opening||0)>=0?'Lena':'Dena'} · ${esc(p.asOf||'')}</p><div class="entry entry-title"><span>Entries</span><span>Diye / Udhar</span><span>Mile / Dena</span></div>`+entryHTML(es.filter(e=>e.partyId===p.id&&matches(e)));$('actions').innerHTML='<button data-entry="collection" class="got">Wasooli / وصولی</button><button data-entry="payment" class="give">Payment / ادائیگی</button><button data-more>+</button>';
 }else{const bs=parties().map(p=>balance(p,es));$('summary').innerHTML=`<div><strong class="red">${money(bs.filter(x=>x>0).reduce((a,b)=>a+b,0))}</strong><small>Hum ne lene hain</small></div><div><strong class="green">${money(-bs.filter(x=>x<0).reduce((a,b)=>a+b,0))}</strong><small>Hum ne dene hain</small></div>`;const ps=parties().filter(p=>(tab==='all'||p.category===tab)&&accountMatches(p,q)).sort((a,b)=>a.name.localeCompare(b.name));$('list').innerHTML=ps.map(p=>{const b=balance(p,es);return `<button class="party" data-party="${esc(p.id)}"><span class="avatar">${esc(p.name.slice(0,2).toUpperCase())}</span><span class="name"><b>${esc(p.name)}</b><small>${esc(p.phone||p.category)}</small></span><span class="amount"><b class="${b>=0?'red':'green'}">${money(Math.abs(b))}</b><small>${b>0?'Lene hain':b<0?'Dene hain':'Barabar'}</small></span></button>`}).join('')||'<div class="empty"><strong>Apna khata shuru karein</strong><p>Naya account banayein ya PDF import karein.</p></div>';$('actions').innerHTML='<button data-add>＋ Naya account</button>'+(owner()?'<button data-import>PDF Import</button>':'')}
 }else if(view==='daily'){
 const d=daily(date,es,closings());$('summary').innerHTML=`<div><small>Sale + Wasooli + Kal ka Change</small><strong>${money(d.sale+d.collection+d.opening)}</strong></div><div><small>${d.closed?'Closing farq':'Closing abhi baqi'}</small><strong class="${d.difference?'red':'green'}">${d.closed?money(d.difference):'—'}</strong></div>`;
 $('list').innerHTML=`<label>Tareekh<input id="dayPicker" type="date" value="${date}"></label>${!d.openingKnown?'<p class="warning">Pichhle din ka Change nahi mila. Closing mein opening Change likhein.</p>':''}<div class="daily-grid">${[['Sale',d.sale],['Wasooli',d.collection],['Akhrajat + Payments',d.expense+d.payment],['Kal ka Change',d.opening],['Aaj ka Change',d.change],['Closing Cash',d.cash]].map(([k,v])=>`<div><small>${k}</small><strong>${money(v)}</strong></div>`).join('')}</div><p class="stat-note">Sale + Wasooli + Kal ka Change − Akhrajat − Aaj ka Change − Closing Cash</p>`+entryHTML(es.filter(e=>e.date===date&&matches(e)));$('dayPicker').onchange=e=>{date=e.target.value||today();render()};$('actions').innerHTML='<button data-entry="sale">＋ Sale</button><button data-entry="collection">Wasooli</button><button data-entry="expense">Kharcha</button>'+(owner()?'<button data-closing>Closing</button>':'');
 }else if(view==='expenses'){
 const accounts=[...new Set(['Bijli','Kiraya','Transport','Dukan ka kharcha',...all('expenseAccount').map(a=>a.name),...es.filter(e=>e.kind==='expense').map(e=>e.account)])];$('summary').innerHTML=`<div><small>Total kharcha + party payments</small><strong>${money(es.filter(e=>['expense','payment'].includes(e.kind)).reduce((s,e)=>s+e.amount,0))}</strong></div>`;$('list').innerHTML=accounts.filter(a=>norm(a).includes(norm(q))).map(a=>`<button class="party" data-expense="${esc(a)}"><span class="name"><b>${esc(a)}</b><small>Kharchay ka account</small></span><b>${money(es.filter(e=>e.account===a&&e.kind==='expense').reduce((s,e)=>s+e.amount,0))}</b></button>`).join('')+'<h3>Entries / Party payments</h3>'+entryHTML(es.filter(e=>['expense','payment'].includes(e.kind)&&matches(e)));$('actions').innerHTML='<button data-expense-add>＋ Kharcha account</button><button data-entry="payment">Party payment</button>';
 }else{const cs=closings().sort((a,b)=>b.date.localeCompare(a.date));$('summary').innerHTML=`<div><small>Closing Cash account · aakhri counted cash</small><strong>${money(cs[0]?.cash||0)}</strong><small>Har din ki ginti alag hai; yeh jama-shuda balance nahi.</small></div>`;$('list').innerHTML=cs.map(c=>`<button class="party" data-day="${c.date}"><span class="name"><b>${c.date}</b><small>Change ${money(c.change)}</small></span><b>${money(c.cash)}</b></button>`).join('')||'<div class="empty">Daily Sale mein pehli closing save karein.</div>';$('actions').innerHTML='<button data-daily>Daily Sale kholein</button>'}
}
async function save(data,existing){if(!session||!loaded)throw Error('Data load hone ka intezar karein');const payload={...data,id:existing?.id||data.id||crypto.randomUUID(),createdAt:existing?.createdAt||Date.now(),by:existing?.by||session.user.uid,updatedAt:Date.now(),updatedBy:session.user.uid,rev:(existing?.rev||0)+1};if(existing||data.type==='closing'){if(!owner())throw Error('Sirf malik edit kar sakta hai');await cloud.edit(payload,existing?.rev||0)}else cloud.add(payload).catch(error);$('dialog').close();notice(navigator.onLine?'Save bheja gaya; Sync status dekhein.':'Offline: entry device par, online hone par Sync hogi.')}
function formSave(fn){const f=$('dialogBody').querySelector('form');f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('[type=submit]');b.disabled=true;try{await fn(f)}catch(e){error(e)}finally{b.disabled=false}}}
function accountForm(p=null){modal(p?'Account edit':'Naya account',`<form><label>Naam<input name="name" required maxlength="160" value="${esc(p?.name||'')}"></label><label>Mobile<input name="phone" inputmode="tel" value="${esc(p?.phone||'')}"></label><label>Qism<select name="category"><option>Customer</option><option ${p?.category==='Supplier'?'selected':''}>Supplier</option></select></label>${!p&&owner()?'<label>Shuru ka baqaya<input name="opening" type="number" min="0" step="0.01" value="0"></label><select name="side"><option value="1">Hum ne lene hain</option><option value="-1">Hum ne dene hain</option></select>':''}<button type="submit">Save account</button></form>`);formSave(f=>{if(!f.elements.name.value.trim())throw Error('Naam likhein');return save({...p,type:'party',name:f.elements.name.value.trim(),phone:f.elements.phone.value.trim(),category:f.elements.category.value,...(!p?{opening:owner()?cents(f.elements.opening.value)*Number(f.elements.side.value):0,asOf:today()}:{})},p)})}
function entryForm(kind,pid=selected,existing=null,account=''){
 let picked=existing?.partyId||pid;const requires=['payment','collection','credit','borrow'].includes(kind),accs=[...new Set(['Bijli','Kiraya','Transport','Dukan ka kharcha',...all('expenseAccount').map(a=>a.name)])];
 modal(TYPES[kind],`<form>${requires?'<label>Account search<input id="partySearch" type="search" placeholder="Naam / mobile"></label><div id="partyChoices" class="picker"></div><div id="picked" class="selected-account"></div>':''}${kind==='expense'?`<label>Kharcha account<select name="account">${accs.map(a=>`<option ${a===(existing?.account||account)?'selected':''}>${esc(a)}</option>`).join('')}</select></label>`:''}<label>Raqam (Rs)<input name="amount" type="number" min="0.01" step="0.01" required value="${existing?existing.amount/100:''}" inputmode="decimal"></label><label>Tareekh<input name="date" type="date" required value="${existing?.date||(view==='daily'?date:today())}"></label><label>Note<textarea name="note" rows="2" maxlength="1000">${esc(existing?.note||'')}</textarea></label><p class="stat-note">${['credit','borrow'].includes(kind)?'Sirf khate ka baqaya badlega. Daily cash sale mein shamil nahi hoga.':'Ek entry khate aur daily hisaab mein ek baar lagegi.'}</p><div class="form-actions"><button type="submit">Save / محفوظ کریں</button>${existing?'<button type="button" id="deleteEntry" class="danger">Delete entry</button>':''}</div></form>`);
 if(requires){const choose=()=>{$('picked').textContent=picked?party(picked)?.name||'Account nahi mila':'Account select karein';$('partyChoices').innerHTML=parties().filter(p=>accountMatches(p,$('partySearch').value)).slice(0,30).map(p=>`<button type="button" data-pick="${p.id}">${esc(p.name)} · ${esc(p.phone)}</button>`).join('')};$('partySearch').oninput=choose;$('partyChoices').onclick=e=>{const b=e.target.closest('[data-pick]');if(b){picked=b.dataset.pick;$('picked').textContent=party(picked).name;$('partyChoices').innerHTML=''}};choose()}
 formSave(f=>{const amount=cents(f.elements.amount.value);if(!amount)throw Error('Raqam likhein');if(requires&&!party(picked))throw Error('Account select karein');return save({...existing,type:'entry',kind,partyId:requires?picked:'',account:kind==='expense'?f.elements.account.value:'',amount,date:f.elements.date.value,note:f.elements.note.value},existing)});
 if(existing)$('deleteEntry').onclick=()=>{if(confirm('Entry delete karni hai? Khata aur daily hisaab dono badlenge.'))save({...existing,deleted:true},existing).catch(error)};
}
function closingForm(){const c=closings().find(c=>c.date===date),prev=closings().find(c=>c.date===yesterday(date));modal('Closing · '+date,`<form>${!prev?`<label>Kal ka Change (opening)<input name="opening" type="number" min="0" step="0.01" required value="${c?.opening!=null?c.opening/100:''}"></label>`:`<p>Kal ka Change: ${money(prev.change)}</p>`}<label>Aaj counted Change<input name="change" type="number" min="0" step="0.01" required value="${c?c.change/100:''}"></label><label>Counted Closing Cash<input name="cash" type="number" min="0" step="0.01" required value="${c?c.cash/100:''}"></label><p>Change agle din ki opening banega. Cash apne account mein save hoga.</p><button type="submit">Save closing</button></form>`);formSave(f=>save({type:'closing',id:'closing-'+date,date,change:cents(f.elements.change.value),cash:cents(f.elements.cash.value),...(f.elements.opening?{opening:cents(f.elements.opening.value)}:{})},c))}
$('profile').onclick=()=>owner()?accountForm(party(selected)):notice('Account edit sirf malik kar sakta hai');
document.querySelector('main').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.party)route('khata',d.party);if(d.entry)entryForm(d.entry);if('add'in d)accountForm();if(d.edit){const x=entries().find(x=>x.id===d.edit);entryForm(x.kind,x.partyId,x)}if('closing'in d)closingForm();if(d.day){date=d.day;route('daily')}if('daily'in d)route('daily');if(d.expense)entryForm('expense',null,null,d.expense);if('expenseAdd'in d){modal('Kharcha account','<form><label>Naam<input name="name" required maxlength="100"></label><button type="submit">Save</button></form>');formSave(f=>{const name=f.elements.name.value.trim();if(!name)throw Error('Naam likhein');return save({type:'expenseAccount',name})})}if('more'in d){modal('Khate ki entry','<div class="menu"><button id="credit">Udhar diya / Lene hain</button><button id="borrow">Udhar liya / Dene hain</button></div>');$('credit').onclick=()=>entryForm('credit');$('borrow').onclick=()=>entryForm('borrow')}if('import'in d)importForm()});
function report(){const p=party(selected),es=entries();let heading='Accounts report',headers=['Account','Mobile','Lena','Dena'],rows=parties().filter(p=>accountMatches(p,$('search').value)&&(tab==='all'||p.category===tab)).map(p=>{const b=balance(p,es);return[p.name,p.phone,money(Math.max(b,0)),money(Math.max(-b,0))]});let sub='As of '+today();if(p){heading=p.name+' — Khata';headers=['Tareekh','Entry','Note','Raqam'];rows=es.filter(e=>e.partyId===p.id&&matches(e)).sort((a,b)=>a.date.localeCompare(b.date)).map(e=>[e.date,TYPES[e.kind],e.note,money(e.amount)]);const b=balance(p,es);sub=`Opening ${money(Math.abs(p.opening||0))} (${(p.opening||0)>=0?'Lena':'Dena'}) · Current ${money(Math.abs(b))} (${b>=0?'Lena':'Dena'}) · Filter ${$('from').value||'Start'} to ${$('to').value||today()}`}
if(view==='daily'){heading='Daily Sale · '+date;const d=daily(date,es,closings());headers=['Khata','Raqam'];rows=[['Sale',money(d.sale)],['Wasooli',money(d.collection)],['Kal ka Change',money(d.opening)],['Akhrajat + payment',money(d.expense+d.payment)],['Aaj ka Change',money(d.change)],['Closing Cash',money(d.cash)],['Farq',d.closed?money(d.difference):'Closing baqi']];sub='Sale + Wasooli + Kal ka Change − Akhrajat − Change − Cash';rows.push(...es.filter(e=>e.date===date).map(e=>[TYPES[e.kind]+' · '+(party(e.partyId)?.name||e.account||'')+' · '+e.note,money(e.amount)]))}
if(view==='cash'){heading='Closing Cash account';headers=['Tareekh','Counted Cash','Counted Change'];rows=closings().sort((a,b)=>a.date.localeCompare(b.date)).map(c=>[c.date,money(c.cash),money(c.change)])}if(view==='expenses'){heading='Akhrajat report';headers=['Tareekh','Account','Note','Raqam'];rows=es.filter(e=>['expense','payment'].includes(e.kind)&&matches(e)).map(e=>[e.date,party(e.partyId)?.name||e.account,e.note,money(e.amount)])}
$('printArea').innerHTML=`<h1>Sam · Noor Traders</h1><h2>${esc(heading)}</h2><p>${esc(sub)}</p><table><thead><tr>${headers.map(h=>'<th>'+esc(h)+'</th>').join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')}</tbody></table><p>Generated ${esc(new Date().toLocaleString('en-PK',{timeZone:'Asia/Karachi'}))}</p>`;window.print()}
$('report').onclick=report;
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),20000)}
function importForm(){if(!owner())return;modal('DigiKhata PDF import',`<label>All Parties List PDF<input id="importFile" type="file" accept="application/pdf"></label><p class="stat-note">Aapka format: You'll Give = Lene hain · You'll Get = Dene hain. Balance ko daily sale mein add nahi kiya jayega.</p><div id="importStatus"></div>`);$('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>8e6){$('importStatus').textContent='PDF 8 MB se chhoti honi chahiye';return}try{$('importStatus').textContent='Report parhi ja rahi hai…';const bytes=new Uint8Array(await file.arrayBuffer()),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');if(records.some(r=>r.id==='import-'+hash))throw Error('Yeh PDF pehle import ho chuki hai');const pdfjs=await import('./vendor/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.mjs',import.meta.url).href;const {readReport}=await import('./pdf-import.js'),result=await readReport(bytes,pdfjs);importDraft={...result,hash,file,bytes};const duplicates=result.rows.filter(r=>parties().some(p=>norm(p.name)===norm(r.name)||(r.details.replace(/\D/g,'').length>=10&&p.phone?.replace(/\D/g,'')===r.details.replace(/\D/g,''))));if(duplicates.length)throw Error(duplicates.length+' accounts pehle mojood hain. Existing balances overwrite nahi kiye. Malik se records milayein.');$('importStatus').innerHTML=`<p><b>${result.rows.length} accounts</b> · Lena ${money(result.give)} · Dena ${money(result.get)}</p><div class="import-preview">${result.rows.map(r=>`<div class="source-row"><span>${esc(r.name)}</span><span>${money(r.give||r.get)} · ${r.give?'Lena':r.get?'Dena':'0'}</span></div>`).join('')}</div><label>Report ki tareekh<input id="importDate" type="date" value="${today()}" required></label><button id="confirmImport">Confirm import</button>`;$('confirmImport').onclick=async()=>{const b=$('confirmImport');b.disabled=true;try{if(!$('importDate').value)throw Error('Tareekh dein');await cloud.importPDF(importDraft,$('importDate').value);$('dialog').close();notice('PDF aur opening balances import ho gaye')}catch(e){error(e);b.disabled=false}}}catch(e){$('importStatus').textContent=e.message}}}
$('settings').onclick=()=>{modal('Settings · v1.0.0',`<div class="menu"><button id="backup">Backup download</button>${owner()?'<label>Backup restore<input id="restore" type="file" accept="application/json"></label><button id="imports">Saved PDF reports</button><button id="changePass">Malik password change</button>':''}<button id="logout">Logout</button><p class="stat-note">PDF button par Print menu se “Save as PDF” choose karein. Naye mobile par pehla login internet se karein. Pending entries Sync hone tak isi device par rehti hain.</p></div>`);$('logout').onclick=()=>cloud.controller.logout();$('backup').onclick=()=>download('sam-khata-backup-'+today()+'.json',new Blob([JSON.stringify({format:'sam-blue-khata-v1',records},null,2)],{type:'application/json'}));if(owner()){
$('restore').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const data=JSON.parse(await f.text());if(data.format!=='sam-blue-khata-v1'||!Array.isArray(data.records))throw Error('Backup format durust nahi');if(!confirm(data.records.length+' records restore karein?'))return;await cloud.restore(data.records);$('dialog').close();notice('Backup restore ho gaya')}catch(e){error(e)}};
$('imports').onclick=()=>{modal('Saved PDF reports',all('import').map(r=>`<button data-download-pdf="${r.id}">${esc(r.filename)} · ${esc(r.date)}</button>`).join('')||'<p>Abhi koi PDF import nahi hui.</p>');$('dialogBody').onclick=e=>{const b=e.target.closest('[data-download-pdf]');if(b){const chunks=all('pdfChunk').filter(c=>c.importId===b.dataset.downloadPdf).sort((a,b)=>a.order-b.order),r=records.find(r=>r.id===b.dataset.downloadPdf);const raw=atob(chunks.map(c=>c.data).join(''));download(r.filename,new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type:'application/pdf'}))}}};
$('changePass').onclick=()=>{modal('Malik password change','<form><label>Purana password<input name="old" type="password" required></label><label>Naya password<input name="new" type="password" minlength="6" required></label><button type="submit">Save password</button></form>');formSave(async f=>{await cloud.controller.changePassword(f.elements.old.value,f.elements.new.value);$('dialog').close();notice('Password badal gaya')})}
}};
async function sync(){try{if(cloud){await cloud.controller.resume();if(session){$('syncStatus').textContent='Sync ho raha hai…';await cloud.wait();$('syncStatus').textContent='Data synced'}}const r=await fetch('./version.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Update check failed');const v=await r.json();if(v.version!=='1.0.0'){if(confirm('Naya version '+v.version+' tayyar hai. Reload karein?')){const reg=await navigator.serviceWorker?.getRegistration();await reg?.update();location.reload()}}else notice('Version 1.0.0 latest hai')}catch(e){notice('Sync / update mukammal nahi hua. Internet check karein.')}}
document.querySelectorAll('.sync').forEach(b=>b.onclick=sync);
import('./cloud.js').then(async m=>{cloud=await m.connect({reset(){session=null;loaded=false;records=[];unsub?.();unsub=null;document.querySelector('main').hidden=true;$('login').hidden=false;$('dialog').close();$('printArea').innerHTML='';$('dialogBody').innerHTML=''},onSession(s){session=s;$('password').value='';$('login').hidden=true;document.querySelector('main').hidden=false;$('syncStatus').textContent='Data load ho raha hai…';unsub=cloud.listen(snap=>{records=snap.rows;loaded=true;$('syncStatus').textContent=snap.pending?'Device par saved · Cloud Sync baqi':snap.cached?'Offline / cached data':'Cloud synced';render()},e=>{$('syncStatus').textContent='Data load nahi hua: '+e.code;error(e)});render()},onError(e,role){$('loginMessage').textContent=m.loginErrorMessage(e,role)}});$('loginMessage').textContent='Purana malik login ya staff ka saved mobile password use karein.';$('loginForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await cloud.controller.login({role:$('role').value,username:$('username').value,password:$('password').value})}catch(e){$('loginMessage').textContent=m.loginErrorMessage(e,$('role').value)}finally{b.disabled=false}}}).catch(e=>{$('loginMessage').textContent='Connection load nahi hua. Pehli dafa internet se kholein, phir reload karein.';console.error(e)});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);
try{document.modelContext?.registerTool({name:'read_khata_summary',description:'Read current signed-in khata totals',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){if(!session||!loaded)throw Error('Login and data loading required');return{accounts:parties().length,date,daily:daily(date,entries(),closings())}}})}catch{}
