import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import * as authSDK from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import {initializeFirestore,persistentLocalCache,persistentMultipleTabManager,collection,doc,getDoc,setDoc,onSnapshot,runTransaction,writeBatch,waitForPendingWrites} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
import {createAuthController,loginErrorMessage} from './auth-controller.js';
import {firebaseConfig,BUSINESS_ID} from './config.js';
export {loginErrorMessage};
export async function connect(callbacks){const app=initializeApp(firebaseConfig,'blue-khata'),auth=authSDK.getAuth(app);await authSDK.setPersistence(auth,authSDK.browserLocalPersistence);const db=initializeFirestore(app,{localCache:persistentLocalCache({tabManager:persistentMultipleTabManager()})});const col=collection(db,'businesses',BUSINESS_ID,'blueKhata'),ref=id=>doc(col,id),other=(name,id)=>doc(db,'businesses',BUSINESS_ID,name,id);
const controller=createAuthController({auth,sdk:authSDK,accounts:{async getSession(uid){const s=await getDoc(other('blueStaffSessions',uid));return s.exists()?s.data():(await getDoc(other('staffSessions',uid))).data()},async getAccount(phone){return (await getDoc(other(phone.length===64?'blueStaffKeys':'staffAccounts',phone))).data()},async createPasswordSession(uid,password,phone){const cfg=await getDoc(other('blueAccess','config'));if(cfg.exists()){const credentialId=await passwordKey(password);await setDoc(other('blueStaffSessions',uid),{credentialId,createdAt:Date.now()})}else{if(!phone)throw Error('Malik pehle Settings mein mulazim password set karein');await setDoc(other('staffSessions',uid),{phone,createdAt:Date.now()})}},async createSession(uid,phone){await setDoc(other('staffSessions',uid),{phone,createdAt:Date.now()})}},onReset:callbacks.reset,onSession:s=>setTimeout(()=>{if(auth.currentUser?.uid===s.user.uid)callbacks.onSession(s)},0),onError:callbacks.onError});
async function passwordKey(password){const enc=new TextEncoder(),key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode('noor-traders-blue-staff-v1'),iterations:210000,hash:'SHA-256'},key,256);return [...new Uint8Array(bits)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function setStaffPassword(password){if(password.length<10)throw Error('Kam az kam 10 haroof ka password rakhein');const key=await passwordKey(password);await runTransaction(db,async tx=>{const cfg=await tx.get(other('blueAccess','private'));if(cfg.exists()&&cfg.data().key!==key)tx.delete(other('blueStaffKeys',cfg.data().key));tx.set(other('blueStaffKeys',key),{active:true,loginEnabled:true,name:'Mulazim'});tx.set(other('blueAccess','private'),{key});tx.set(other('blueAccess','config'),{enabled:true})})}
function valid(r){if(!r||typeof r.id!=='string'||!/^[a-zA-Z0-9_-]{1,160}$/.test(r.id)||!['party','entry','closing','expenseAccount','dayPhoto','import','pdfChunk'].includes(r.type))throw Error('Invalid backup record');if(r.type==='party'&&(typeof r.name!=='string'||!Number.isSafeInteger(r.opening)))throw Error('Invalid account');if(r.type==='entry'&&(!Number.isSafeInteger(r.amount)||r.amount<=0||!['sale','collection','payment','expense','credit','borrow','purchaseCash'].includes(r.kind)))throw Error('Invalid entry');if(['closing','entry'].includes(r.type)&&!/^\d{4}-\d{2}-\d{2}$/.test(r.date||''))throw Error('Invalid date');if(r.type==='closing'&&(!['cash','change','opening'].some(k=>r[k]!=null)||['cash','change','opening'].some(k=>r[k]!=null&&(!Number.isSafeInteger(r[k])||r[k]<0))))throw Error('Invalid closing');return r}
return {controller,setStaffPassword,wait:()=>waitForPendingWrites(db),listen(next,fail){return onSnapshot(col,{includeMetadataChanges:true},s=>next({rows:s.docs.map(d=>({...d.data(),id:d.id})),pending:s.metadata.hasPendingWrites,cached:s.metadata.fromCache}),fail)},add:r=>setDoc(ref(r.id),valid(r)),edit(r,rev){valid(r);return runTransaction(db,async tx=>{const s=await tx.get(ref(r.id));if((s.exists()?s.data().rev||0:0)!==rev)throw Error('Record doosre device par badal gaya. Dobara khol kar edit karein.');tx.set(ref(r.id),r)})},async importPDF(d,date){if(!auth.currentUser||auth.currentUser.isAnonymous)throw Error('Malik login required');if(!navigator.onLine)throw Error('Import ke liye internet chahiye');const id='import-'+d.hash,uid=auth.currentUser.uid,stamp=Date.now(),base={by:uid,updatedBy:uid,createdAt:stamp,updatedAt:stamp,rev:1};let raw='';for(let i=0;i<d.bytes.length;i+=16000)raw+=String.fromCharCode(...d.bytes.subarray(i,i+16000));const b64=btoa(raw),chunks=[];for(let i=0;i<b64.length;i+=400000)chunks.push(b64.slice(i,i+400000));if(d.rows.length+chunks.length+1>450)throw Error('Report bohat bari hai; 450 records se chhota hissa import karein');await runTransaction(db,async tx=>{const seen=await tx.get(ref(id));if(seen.exists())throw Error('PDF pehle import ho chuki hai');for(const r of d.rows){const pid='pdf-'+d.hash+'-'+r.sourceRow;tx.set(ref(pid),{...base,id:pid,type:'party',name:r.name,details:r.details,phone:r.details.replace(/[^\d+\-]/g,''),category:'Customer',opening:r.give-r.get,asOf:date,importId:id,sourceRow:r.sourceRow})}chunks.forEach((data,i)=>{const cid=id+'-chunk-'+i;tx.set(ref(cid),{...base,id:cid,type:'pdfChunk',importId:id,order:i,data})});tx.set(ref(id),{...base,id,type:'import',filename:d.file.name,date,count:d.rows.length,receivable:d.give,payable:d.get,hash:d.hash})})},async restore(rows){if(!navigator.onLine)throw Error('Restore ke liye internet chahiye');const ids=new Set();rows.forEach(r=>{valid(r);if(ids.has(r.id))throw Error('Duplicate backup ID');ids.add(r.id)});const stable=v=>JSON.stringify(v,Object.keys(v).sort());for(let i=0;i<rows.length;i+=100){await runTransaction(db,async tx=>{const group=rows.slice(i,i+100),missing=[];for(const r of group){const snap=await tx.get(ref(r.id));if(snap.exists()){if(stable(snap.data())!==stable(r))throw Error('Existing record backup se different hai. Overwrite nahi kiya; pehle restored records rahenge.')}else missing.push(r)}for(const r of missing)tx.set(ref(r.id),r)})}}};
}
