import {validateExtraRecord,addCustodyMove,appendCashMove,cashLedger,stableRecord} from './finance-tools.js';
import {planImport} from './import-plan.js';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import * as authSDK from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import {initializeFirestore,persistentLocalCache,persistentMultipleTabManager,collection,query,where,doc,getDoc,getDocFromServer,getDocs,getDocsFromServer,getDocsFromCache,setDoc,onSnapshot,runTransaction,writeBatch,waitForPendingWrites} from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
import {createAuthController,loginErrorMessage} from './auth-controller.js?v=1.27.0';
import {firebaseConfig,BUSINESS_ID} from './config.js?v=1.27.0';
export {loginErrorMessage};
export async function connect(callbacks){const app=initializeApp(firebaseConfig,'blue-khata'),auth=authSDK.getAuth(app);await authSDK.setPersistence(auth,authSDK.browserLocalPersistence);const db=initializeFirestore(app,{localCache:persistentLocalCache({tabManager:persistentMultipleTabManager()})});const col=collection(db,'businesses',BUSINESS_ID,'blueKhata'),ref=id=>doc(col,id),other=(name,id)=>doc(db,'businesses',BUSINESS_ID,name,id);
let accessScope='none',offCredential=null;const supplierCol=collection(db,'businesses',BUSINESS_ID,'purchaseSuppliers');
async function loginStep(stage,fn){try{return await fn()}catch(e){if(e.code==='permission-denied')throw Object.assign(new Error(stage),{code:'login/'+stage});throw e}}
const controller=createAuthController({auth,sdk:authSDK,accounts:{async getSession(uid){const s=await loginStep('staff-session-read',()=>getDoc(other('blueStaffSessions',uid)));return s.exists()?s.data():null},async getAccount(phone){return (await loginStep('staff-account-read',()=>getDoc(other('blueStaffKeys',phone)))).data()},async createPasswordSession(uid,password,phone,scope='full'){const cfg=await loginStep('staff-config-read',()=>getDocFromServer(other('blueAccess',scope==='purchase'?'purchaseConfig':'config')));if(cfg.exists()){const credentialId=await passwordKey(password,scope);await loginStep('staff-session-create',()=>setDoc(other('blueStaffSessions',uid),{credentialId,createdAt:Date.now()}))}else{throw Object.assign(new Error('Password setup required'),{code:'login/staff-not-configured'})}}},onReset:()=>{offCredential?.();offCredential=null;accessScope='none';callbacks.reset()},onSession:s=>{accessScope=s.role==='owner'?'full':s.scope;if(s.role==='staff'){const revoke=()=>{if(auth.currentUser?.uid===s.user.uid)void controller.logout().catch(callbacks.onError)};offCredential=onSnapshot(other('blueStaffKeys',s.phone),snap=>{if(snap.metadata.fromCache)return;const key=snap.data();if(!key||key.active!==true||key.loginEnabled===false||(key.scope||'full')!==s.scope)revoke()},e=>{if(e.code==='permission-denied')revoke()})}setTimeout(()=>{if(auth.currentUser?.uid===s.user.uid)callbacks.onSession(s)},0)},onError:callbacks.onError});
async function passwordKey(password,scope='full'){const enc=new TextEncoder(),key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(scope==='purchase'?'noor-traders-blue-purchase-v1':'noor-traders-blue-staff-v1'),iterations:210000,hash:'SHA-256'},key,256);return (scope==='purchase'?'purchase-':'')+[...new Uint8Array(bits)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function setStaffPassword(password,scope='full'){
 if(!['full','purchase'].includes(scope))throw Error('Access select karein');if(password.length<10)throw Error('Kam az kam 10 haroof ka password rakhein');
 const key=await passwordKey(password,scope),privateId=scope==='purchase'?'purchasePrivate':'private',configId=scope==='purchase'?'purchaseConfig':'config';
 if(scope==='purchase')await syncPurchaseSuppliers();
 await runTransaction(db,async tx=>{const cfg=await tx.get(other('blueAccess',privateId));if(cfg.exists()&&cfg.data().key!==key)tx.delete(other('blueStaffKeys',cfg.data().key));tx.set(other('blueStaffKeys',key),{active:true,loginEnabled:true,name:scope==='purchase'?'Purchase Mulazim':'Mulazim',scope});tx.set(other('blueAccess',privateId),{key});tx.set(other('blueAccess',configId),{enabled:true})});
}
async function checkStaffPassword(password,scope='full'){const cfg=await getDocFromServer(other('blueAccess',scope==='purchase'?'purchasePrivate':'private'));if(!cfg.exists())throw Error('Is access ka password abhi save nahi hua');const key=await passwordKey(password,scope);if(key!==cfg.data().key)throw Error('Yeh password saved password se match nahi karta');const credential=await getDocFromServer(other('blueStaffKeys',key));if(!credential.exists()||credential.data().active!==true)throw Error('Login record active nahi. Password dobara Save karein');return true}
const supplierData=r=>({id:r.id,name:r.name,phone:r.phone||''});
async function syncPurchaseSuppliers(){
 if(!auth.currentUser||auth.currentUser.isAnonymous)throw Error('Sirf malik supplier list update kare');
 const snapshot=await getDocsFromServer(col),rows=snapshot.docs.map(d=>({...d.data(),id:d.id})),used=new Set(rows.filter(r=>r.type==='entry'&&r.purchase===true).map(r=>r.partyId));
 const suppliers=rows.filter(r=>r.type==='party'&&!r.deleted&&(r.category==='Supplier'||used.has(r.id)));
 const old=await getDocsFromServer(supplierCol),next=new Map(suppliers.map(r=>[r.id,supplierData(r)])),changes=[];
 for(const d of old.docs){if(!next.has(d.id))changes.push({id:d.id,remove:true});else if(stableRecord(d.data())===stableRecord(next.get(d.id)))next.delete(d.id)}
 for(const [id,data] of next)changes.push({id,data});for(let i=0;i<changes.length;i+=400){const batch=writeBatch(db);for(const c of changes.slice(i,i+400)){const ref=doc(supplierCol,c.id);if(c.remove)batch.delete(ref);else batch.set(ref,c.data)}await batch.commit()}
 return suppliers.length;
}
async function addPurchaseSupplier(name,phone){const id=crypto.randomUUID(),uid=auth.currentUser?.uid;if(!uid)throw Error('Login karein');name=name.trim();if(!name)throw Error('Naam likhein');const stamp=Date.now(),r={id,type:'party',name,phone:phone.trim(),category:'Supplier',opening:0,by:uid,updatedBy:uid,createdAt:stamp,updatedAt:stamp,rev:1};valid(r);const batch=writeBatch(db);batch.set(ref(id),r);batch.set(doc(supplierCol,id),supplierData(r));await batch.commit();return id}
function listenPurchase(next,fail){let ended=false;const stops=[];const stop=()=>{ended=true;stops.forEach(f=>f())};const failed=e=>{stop();fail(e)};let purchases=[],suppliers=[],a=false,b=false,pendingA=false,pendingB=false,cachedA=true,cachedB=true;const emit=()=>{if(!ended&&a&&b)next({rows:[...purchases,...suppliers],pending:pendingA||pendingB,cached:cachedA||cachedB})};const off1=onSnapshot(query(col,where('type','==','entry'),where('purchase','==',true)),{includeMetadataChanges:true},s=>{purchases=s.docs.map(d=>({...d.data(),id:d.id}));a=true;pendingA=s.metadata.hasPendingWrites;cachedA=s.metadata.fromCache;emit()},failed);const off2=onSnapshot(supplierCol,{includeMetadataChanges:true},s=>{suppliers=s.docs.map(d=>({...d.data(),id:d.id,type:'party',category:'Supplier',opening:0}));b=true;pendingB=s.metadata.hasPendingWrites;cachedB=s.metadata.fromCache;emit()},failed);stops.push(off1,off2);if(ended)stop();return stop}
function valid(r){validateExtraRecord(r);if(!r||typeof r.id!=='string'||!/^[a-zA-Z0-9_-]{1,160}$/.test(r.id)||!['party','entry','closing','expenseAccount','dayPhoto','import','pdfChunk','cashCustody','reminder'].includes(r.type))throw Error('Invalid backup record');if(r.type==='party'&&(typeof r.name!=='string'||!Number.isSafeInteger(r.opening)))throw Error('Invalid account');if(r.type==='entry'&&(!Number.isSafeInteger(r.amount)||r.amount<=0||!['sale','collection','payment','expense','credit','borrow','purchaseCash'].includes(r.kind)))throw Error('Invalid entry');if(['closing','entry'].includes(r.type)&&!/^\d{4}-\d{2}-\d{2}$/.test(r.date||''))throw Error('Invalid date');if(r.type==='closing'&&(!['cash','change','opening'].some(k=>r[k]!=null)||['cash','change','opening'].some(k=>r[k]!=null&&(!Number.isSafeInteger(r[k])||r[k]<0))))throw Error('Invalid closing');return r}
return {async cachedBackup(){if(!auth.currentUser||auth.currentUser.isAnonymous)throw Error('Malik login chahiye');const snap=await getDocsFromCache(col);return {format:'sam-blue-khata-v1',records:snap.docs.map(d=>({...d.data(),id:d.id})),exportedAt:new Date().toISOString(),source:'firestore-device-cache',projectId:firebaseConfig.projectId,pending:snap.metadata.hasPendingWrites,completeness:'unknown'}},controller,setStaffPassword,checkStaffPassword,syncPurchaseSuppliers,addPurchaseSupplier,wait:()=>waitForPendingWrites(db),listen(next,fail){if(accessScope==='purchase')return listenPurchase(next,fail);return onSnapshot(col,{includeMetadataChanges:true},s=>next({rows:s.docs.map(d=>({...d.data(),id:d.id})),pending:s.metadata.hasPendingWrites,cached:s.metadata.fromCache}),fail)},add:r=>{if(accessScope==='purchase'&&!(r.type==='entry'&&r.purchase===true&&['purchaseCash','borrow'].includes(r.kind)))throw Error('Sirf Purchase ki ijazat hai');return setDoc(ref(r.id),valid(r))},async edit(r,rev){if(accessScope==='purchase'&&!(r.type==='entry'&&r.purchase===true&&['purchaseCash','borrow'].includes(r.kind)))throw Error('Sirf Purchase ki ijazat hai');valid(r);const isCash=['closing','cashCustody'].includes(r.type),guard=other('blueAccess','cashRevision');let cashSnapshot,guardVersion;
if(isCash){const g=await getDocFromServer(guard);guardVersion=g.exists()?g.data().rev:0;const snapshot=await getDocsFromServer(col);cashSnapshot=snapshot.docs.map(d=>({...d.data(),id:d.id}));}
return runTransaction(db,async tx=>{const s=await tx.get(ref(r.id));const g=isCash?await tx.get(guard):null;const currentGuard=g?.exists()?g.data().rev:0;if(isCash&&currentGuard!==guardVersion)throw Error('Cash doosre device par badli hai. Taza total dekh kar dobara Save karein.');if((s.exists()?s.data().rev||0:0)!==rev)throw Error('Record doosre device par badal gaya. Dobara khol kar edit karein.');if(r.type==='cashCustody'){
 const prev=s.exists()?s.data().moves||[]:[],next=r.moves;
 if(next.length===prev.length+1){
  if(JSON.stringify(next.slice(0,-1))!==JSON.stringify(prev))throw Error('Transfer history badal gayi');
  appendCashMove(cashSnapshot,r.date,prev,next[next.length-1]);
 }else if(cashLedger([...cashSnapshot.filter(x=>x.id!==r.id),r]).rows.some(x=>x.date>=r.date&&x.balance<0))throw Error('Is tabdeeli se baqi cash manfi ho jayegi');
}if(r.type==='closing'&&cashLedger([...cashSnapshot.filter(x=>x.id!==r.id),r]).rows.some(x=>x.date>=r.date&&x.balance<0))throw Error('Is tabdeeli se baqi cash manfi ho jayegi');if(isCash)tx.set(guard,{rev:currentGuard+1});tx.set(ref(r.id),r)})},async importPDF(d,date,progress=()=>{}){if(!auth.currentUser||auth.currentUser.isAnonymous)throw Error('Malik login required');if(!navigator.onLine)throw Error('Import ke liye internet chahiye');progress('Server se maujooda accounts parhe ja rahe hain…');const latest=await getDocs(col),plans=planImport(d.rows,latest.docs.map(x=>({...x.data(),id:x.id})),date,d.hash);const id='import-'+d.hash,uid=auth.currentUser.uid,stamp=Date.now(),base={by:uid,updatedBy:uid,createdAt:stamp,updatedAt:stamp,rev:1};let raw='';for(let i=0;i<d.bytes.length;i+=16000)raw+=String.fromCharCode(...d.bytes.subarray(i,i+16000));const b64=btoa(raw),chunks=[];for(let i=0;i<b64.length;i+=400000)chunks.push(b64.slice(i,i+400000));if(d.rows.length+chunks.length+1>450)throw Error('Report bohat bari hai; 450 records se chhota hissa import karein');await runTransaction(db,async tx=>{const seen=await tx.get(ref(id));if(seen.exists())throw Error('PDF pehle import ho chuki hai');// Verify every affected account and covered entry before any writes.
progress(plans.length+' accounts ki tasdeeq ho rahi hai…');
const checkIds=[...new Set(plans.flatMap(p=>[p.id,...p.covered.map(e=>e.id)]))];
const checked=new Map(await Promise.all(checkIds.map(async id=>[id,await tx.get(ref(id))])));
for(const plan of plans){const current=checked.get(plan.id);if(plan.old?(!current.exists()||(current.data().rev||0)!==(plan.old.rev||0)):current.exists())throw Error('Account badal gaya. PDF dobara khol kar import karein.');for(const e of plan.covered){const v=checked.get(e.id);if(!v.exists()||(v.data().rev||0)!==(e.rev||0))throw Error('Entry badal gayi. Dobara import karein.')}}
progress('Tasdeeq mukammal. Accounts aur PDF server par save ho rahe hain…');
for(const plan of plans){const r=plan.row;tx.set(ref(plan.id),{...(plan.old||{}),...base,id:plan.id,type:'party',name:plan.old?.name||r.name,details:plan.old?.details||r.details,phone:plan.old?.phone||r.details.replace(/[^\d+\-]/g,''),category:plan.old?.category||'Customer',opening:plan.opening,asOf:date,pdfAsOf:date,pdfBalance:plan.target,importId:id,sourceRow:r.sourceRow,createdAt:plan.old?.createdAt||stamp,by:plan.old?.by||uid,rev:(plan.old?.rev||0)+1})}
chunks.forEach((data,i)=>{const cid=id+'-chunk-'+i;tx.set(ref(cid),{...base,id:cid,type:'pdfChunk',importId:id,order:i,data})});tx.set(ref(id),{...base,id,type:'import',filename:d.file.name,date,count:d.rows.length,receivable:d.give,payable:d.get,hash:d.hash,updatedAccounts:plans.filter(p=>p.old).length,newAccounts:plans.filter(p=>!p.old).length,changes:plans.map(p=>({id:p.id,oldOpening:p.old?.opening??null,newOpening:p.opening,pdfBalance:p.target,before:p.before,after:p.after}))})})},async restore(rows){if(!navigator.onLine)throw Error('Restore ke liye internet chahiye');const ids=new Set();rows.forEach(r=>{valid(r);if(ids.has(r.id))throw Error('Duplicate backup ID');ids.add(r.id)});const stable=stableRecord;for(let i=0;i<rows.length;i+=100){await runTransaction(db,async tx=>{const group=rows.slice(i,i+100),missing=[],isCash=group.some(r=>['closing','cashCustody'].includes(r.type)),guard=other('blueAccess','cashRevision'),g=isCash?await tx.get(guard):null;for(const r of group){const snap=await tx.get(ref(r.id));if(snap.exists()){if(stable(snap.data())!==stable(r))throw Error('Existing record backup se different hai. Overwrite nahi kiya; pehle restored records rahenge.')}else missing.push(r)}if(isCash&&missing.length)tx.set(guard,{rev:(g.exists()?g.data().rev:0)+1});for(const r of missing)tx.set(ref(r.id),r)})}}};
}
