// DigiKhata All Parties format: classify amounts by column position, never text order.
export function tableBands(ops,OPS){let m=[1,0,0,1,0,0],stack=[],bands=[];const mul=(a,b)=>[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]];
for(let i=0;i<ops.fnArray.length;i++){const op=ops.fnArray[i],a=ops.argsArray[i];if(op===OPS.save)stack.push([...m]);if(op===OPS.restore)m=stack.pop()||m;if(op===OPS.transform)m=mul(m,a);if(op===OPS.constructPath&&a[0].length===1&&a[0][0]===OPS.rectangle){const [x,y,w,h]=a[1],x0=m[0]*x+m[4],x1=m[0]*(x+w)+m[4],y0=m[3]*y+m[5],y1=m[3]*(y+h)+m[5];if(x0<350&&x1>350&&x1-x0<150)bands.push({top:Math.max(y0,y1),bottom:Math.min(y0,y1)})}}return bands}
export function parsePage(items,bands=[]){
 const words=items.filter(i=>i.str?.trim()).map(i=>({s:i.str.trim(),x:i.transform[4],y:i.transform[5],width:i.width}));
 const nums=words.filter(i=>i.x>=20&&i.x<50&&/^\d+$/.test(i.s)).sort((a,b)=>b.y-a.y),anchors=[];
 for(const n of nums){const prev=anchors.at(-1);if(prev&&prev.lastY-n.y<15){prev.s+=n.s;prev.y=(prev.y+n.y)/2;prev.lastY=n.y}else anchors.push({...n,lastY:n.y})}
 return anchors.map((a,i)=>{const band=bands.find(b=>a.y<b.top&&a.y>b.bottom);const top=band?band.top:i?(anchors[i-1].y+a.y)/2:a.y+22,bottom=band?band.bottom:i<anchors.length-1?(a.y+anchors[i+1].y)/2:a.y-24;const inRow=words.filter(w=>w.y<=top&&w.y>bottom&&w.x>=58).sort((a,b)=>Math.abs(a.y-b.y)>2?b.y-a.y:a.x-b.x);const col=(lo,hi)=>inRow.filter(w=>w.x>=lo&&w.x<hi).reduce((out,w,i,arr)=>out+(i&&(Math.abs(arr[i-1].y-w.y)>2||w.x-arr[i-1].x-arr[i-1].width>1.5)?' ':'')+w.s,'');const amount=s=>{if(!s)return 0;if(!/^[\d,]+(?:\.\d{1,2})?$/.test(s))throw Error('PDF amount samajh nahi aayi: '+s);return Math.round(Number(s.replaceAll(',',''))*100)};return{sourceRow:Number(a.s),name:col(58,141),details:col(141,320),get:amount(col(320,405)),give:amount(col(405,489))}});
}
export async function readReport(bytes,pdfjs){const doc=await pdfjs.getDocument({data:bytes.slice(),useSystemFonts:true}).promise;try{let rows=[],first='';for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),t=await p.getTextContent();if(i===1)first=t.items.map(i=>i.str).join(' ');rows.push(...parsePage(t.items,tableBands(await p.getOperatorList(),pdfjs.OPS)))}if(!first.includes('All Parties List Report'))throw Error('Sirf DigiKhata All Parties List Report supported hai');const count=Number(first.match(/No\.\s*of\s*Parties:\s*(\d+)/i)?.[1]);const totals=[...first.matchAll(/Rs\s*([\d,]+)/g)].slice(0,2).map(m=>Number(m[1].replaceAll(',',''))*100);if(!count||rows.length!==count||rows.some((r,i)=>r.sourceRow!==i+1||!r.name)||totals.length!==2||rows.reduce((s,r)=>s+r.get,0)!==totals[0]||rows.reduce((s,r)=>s+r.give,0)!==totals[1])throw Error('PDF rows / totals match nahi hue. Import roka gaya; report ka format check karein.');return{rows,get:totals[0],give:totals[1]}}finally{await doc.destroy()}}
