/* Independent recovery controls: no Firebase sign-in required to export this device's copy. */
(()=>{
 const dbReady=new Promise((resolve,reject)=>{const r=indexedDB.open('sam-blue-khata-recovery-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('backups');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
 async function get(key){const db=await dbReady;return new Promise((resolve,reject)=>{const r=db.transaction('backups').objectStore('backups').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
 async function put(key,value){const db=await dbReady;return new Promise((resolve,reject)=>{const tx=db.transaction('backups','readwrite');tx.objectStore('backups').put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
 function download(data){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.href=url;a.download='Sam-Khata-Recovery-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
 window.KhataRecovery={get,put,download};
 const msg=document.getElementById('recoveryStatus');
 document.getElementById('emergencyBackup').onclick=async()=>{if(!window.ownerBackupAuthorized){window.pendingOwnerBackup=true;msg.textContent='Full device backup ke liye pehle Malik login karein. Purchase password se full backup nahi khulta.';document.getElementById('role').value='owner';document.getElementById('role').dispatchEvent(new Event('change'));document.getElementById('password').focus();return}const button=document.getElementById('emergencyBackup');button.disabled=true;try{msg.textContent='Is device ka backup parh rahe hain…';let copy=await get('cloud:'+window.khataProjectId);const legacy=await get('cloud');if(window.readKhataCache){try{const cached=await window.readKhataCache();if(cached.records.length){const merged=new Map((copy?.records||[]).map(r=>[r.id,r]));for(const r of cached.records){const prev=merged.get(r.id);if(!prev||(r.updatedAt||0)>=(prev.updatedAt||0))merged.set(r.id,r)}copy={...cached,records:[...merged.values()],completeness:'device-copy-only'}}}catch{}}if(!copy?.records?.length&&legacy?.records?.length)copy={...legacy,projectId:legacy.projectId||'legacy-project-unknown',source:'legacy-device-copy'};if(!copy?.records?.length)throw Error('Is device par data copy nahi mili. Jis phone par khata khulta tha wahan se backup lein.');download(copy);msg.textContent='Device copy download ho gayi. Yeh server ka taza backup hone ki guarantee nahi; file mein copy ka waqt aur pending status hai.'}catch(e){msg.textContent=e.message}finally{button.disabled=false}};
})();
