const CACHE='sam-blue-khata-2.41.0';
const LIB_CACHE='sam-blue-khata-libs-v1';
const ASSETS=['./','./index.html','./style.css','./app.js','./style.css?v=2.41.0','./app.js?v=2.41.0','./recovery.js?v=2.41.0','./recovery.js','./local-mode.js','./account-transfer.js','./search-focus.js','./cash-links.js','./optimistic.js','./entry-status.js','./live-data.js','./pos-ledger.js','./pos-ledger.js?v=2.41.0','./pos-stock.js','./pos-stock.js?v=2.41.0','./sale.js','./sale.js?v=2.41.0','./purchase.js', './galla.js','./purchase.js?v=2.41.0', './galla.js?v=2.41.0', './audit.js?v=2.41.0','./notes.js?v=2.41.0','./barcode.js?v=2.41.0','./geo-guard.js','./geo-guard.js?v=2.41.0','./manifest.webmanifest','./icon-192.png','./icon-512.png','./icon-maskable-512.png','./apple-touch-icon.png','./favicon-64.png','./smart-search.js','./ai-tally.js','./tolai.js','./tolai.js?v=2.41.0','./ai-tally.js?v=2.41.0','./smart-search.js?v=2.41.0','./model.js','./finance-tools.js','./import-plan.js','./cloud.js','./cloud.js?v=2.41.0','./auth-controller.js','./auth-controller.js?v=2.41.0','./config.js','./config.js?v=2.41.0','./pdf-import.js','./pdf-export.js','./vendor/jspdf.js','./vendor/html2canvas.js','./vendor/pdf.mjs','./vendor/pdf.worker.mjs'];
const isLibrary=u=>u.hostname==='www.gstatic.com'&&u.pathname.startsWith('/firebasejs/12.18.0/')||u.origin===location.origin&&u.pathname.includes('/vendor/');
self.addEventListener('install',e=>e.waitUntil((async()=>{const want=CACHE.replace('sam-blue-khata-','');const vr=await fetch(new Request(new URL('./version.json?sw='+Date.now(),location.href),{cache:'no-store'}));const vj=await vr.json();if(String(vj.version)!==want)throw Error('GitHub par naya version abhi poora chalu nahi ('+vj.version+' != '+want+') — baad mein dobara');const core=await caches.open(CACHE),libs=await caches.open(LIB_CACHE);await Promise.all(ASSETS.map(async path=>{const request=new Request(new URL(path,location.href));if(isLibrary(new URL(request.url))){const hit=await caches.match(request);if(hit){await libs.put(request,hit);return}const r=await fetch(request);if(!r.ok)throw Error('Library load failed');await libs.put(request,r)}else{const r=await fetch(new Request(request.url,{cache:'reload'}));if(!r.ok)throw Error('file nahi mili: '+request.url);await core.put(request,r)}}));await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('sam-blue-khata-')&&key!==CACHE&&key!==LIB_CACHE)await caches.delete(key);await self.clients.claim()})()));
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.pathname.endsWith('version.json')||u.pathname.endsWith('sw.js'))return;if(u.origin!==location.origin&&!isLibrary(u))return;
 const html=e.request.mode==='navigate'||u.pathname.endsWith('/index.html');
 e.respondWith((async()=>{const cache=await caches.open(isLibrary(u)?LIB_CACHE:CACHE);if(!html){const hit=await cache.match(e.request);if(hit)return hit}try{const response=await fetch(e.request,{cache:html?'no-cache':'default'});if(response.ok){const write=cache.put(e.request,response.clone());e.waitUntil(write.catch(()=>{}))}return response}catch(error){const hit=await cache.match(e.request)|| (html?await cache.match(new URL('./index.html',location.href)):null);if(hit)return hit;throw error}})());
});
// v2.23: 🔔 PUSH — Cloud Function (FCM) data message -> notification bar mein, jab tak khud na hatayein. Tap = wohi note / khata.
self.addEventListener('push',e=>{let p={};try{p=e.data?e.data.json():{}}catch{try{p={data:{title:'Blue Khata',body:e.data.text()}}}catch{}}
 const d=p.data||p.notification||p||{},title=String(d.title||'Blue Khata').slice(0,120);
 e.waitUntil(self.registration.showNotification(title,{body:String(d.body||'').slice(0,240),tag:String(d.tag||'bk'),renotify:true,requireInteraction:true,icon:'./icon-192.png',badge:'./favicon-64.png',vibrate:[300,150,300],data:{url:String(d.url||'./')}}));});
self.addEventListener('notificationclick',e=>{e.notification.close();const url=new URL(e.notification.data?.url||'./',self.registration.scope).href;
 e.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>{for(const w of ws){if(w.url.startsWith(self.registration.scope)&&'focus' in w){try{w.navigate?.(url)}catch{}return w.focus()}}return self.clients.openWindow(url)}));});
